### PR TITLE
AutoPropertiesProtocol

### PR DESCRIPTION
**Pull request by AliSoftware**
Typically useful for Dependency Injection via Protocol Composition, as explained by @krzysztofzablocki in [this blog post](http://merowing.info/2017/04/using-protocol-compositon-for-dependency-injection/)

\cc @ilyapuchka

_Note that I still continue to push my templates ideas here instead of directly in Sourcery because you don't have either docs / instructions / context associated with your sample templates, nor demo code using them, so I feel having a dedicated repo with each template explained and showed in actual use case examples is better_

### CODE REVIEW

**Comment by ilyapuchka** [comment]
Nice template =)
We have a section with all embedded templates in the docs [here](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/equatable.html), but yeah, we should add contribution guidelines for that. And I think keeping templates in a separate repo will be better than keeping all of them next to source code so maybe we will move them if @krzysztofzablocki will be up for it.

**Comment by krzysztofzablocki** [comment]
I think I prefer them in the main repo, especially since we now have tests against new releases that keep them working

**Comment by AliSoftware** [comment]
I'm ok with adding them on the main repo, but tbh as a Sourcery user I think there's a lack in documentation about each project.
That's also why I created a separate repo, to have that explicit README (what does the template do, what's its use case, how to use it step by step — because some people might not be familiar with the phantom protocol trick and which annotations to use, etc), and also a a sample use case (but tests will do)

If you plan to organise the templates repo in Sourcery in a nice way so that people find documentation for each template then I'm totally for it :wink:

**Comment by krzysztofzablocki** [comment]
thats what docs are for, we need to improve readme and link to 3rd party tutorial etc, I'll work on that when I'm back from my personal time

**Comment by AliSoftware** [comment]
Ha must have missed them. Maybe the only thing to improve is docs discovery then, if they already exist? 
Where are the docs for provided templates located so I can add my templates docs via PR?

**Comment by ilyapuchka** [comment]
They are all currently in Example section of our docs - https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/index.html
You basically need to add *.md file in guides and reference it in categories in jazzy.yaml, then docs will be updated on next release

**Comment by AliSoftware** [comment]
Ah, right, thx. Will try to find some time to make a PR soon then 👍

**Pull request merged**
